import { z } from "zod";

/**
 * AI Day Plan Item - single task/item in a daily plan
 */
export const AIDayPlanItemSchema = z.object({
  text: z.string().min(1, "Item text cannot be empty"),
  order: z.number().int().min(0, "Order must be non-negative"),
});

/**
 * AI Day Plan - complete daily plan generated by AI
 */
export const AIDayPlanSchema = z.object({
  title: z.string().min(1, "Plan title cannot be empty"),
  items: z
    .array(AIDayPlanItemSchema)
    .min(1, "Plan must have at least one item")
    .refine(
      (items) => {
        const orders = items.map((item) => item.order);
        const uniqueOrders = new Set(orders);
        return orders.length === uniqueOrders.size;
      },
      { message: "Item orders must be unique" }
    ),
});

/**
 * AI Week Summary - weekly planning guidance from AI
 */
export const AIWeekSummarySchema = z.object({
  focusAreas: z
    .array(z.string().min(1, "Focus area cannot be empty"))
    .min(1, "Must have at least one focus area")
    .max(5, "Maximum 5 focus areas"),
  intensity: z.enum(["light", "moderate", "intensive"]),
  notes: z.string().min(1, "Notes cannot be empty"),
});

// Type exports for TypeScript
export type AIDayPlanItem = z.infer<typeof AIDayPlanItemSchema>;
export type AIDayPlan = z.infer<typeof AIDayPlanSchema>;
export type AIWeekSummary = z.infer<typeof AIWeekSummarySchema>;
