import { z } from "zod";

/**
 * AI Day Plan Item - single task/item in a daily plan
 */
export const AIDayPlanItemSchema = z.object({
  text: z.string().min(1, "Item text cannot be empty"),
  order: z.number().int().min(0, "Order must be non-negative"),
});

/**
 * AI Day Plan - complete daily plan generated by AI
 */
export const AIDayPlanSchema = z.object({
  title: z.string().min(1, "Plan title cannot be empty"),
  items: z
    .array(AIDayPlanItemSchema)
    .min(1, "Plan must have at least one item")
    .refine(
      (items) => {
        const orders = items.map((item) => item.order);
        const uniqueOrders = new Set(orders);
        return orders.length === uniqueOrders.size;
      },
      { message: "Item orders must be unique" }
    ),
});

/**
 * AI Week Summary - weekly planning guidance from AI
 */
export const AIWeekSummarySchema = z.object({
  focusAreas: z
    .array(z.string().min(1, "Focus area cannot be empty"))
    .min(1, "Must have at least one focus area")
    .max(5, "Maximum 5 focus areas"),
  intensity: z.enum(["light", "moderate", "intensive"]),
  notes: z.string().min(1, "Notes cannot be empty"),
});

/**
 * Weak area input for planner
 */
export const WeakAreaInputSchema = z.object({
  topicId: z.string().cuid(),
  topicName: z.string().min(1),
  score: z.number().min(0).max(100),
  attempts: z.number().int().min(0),
});

/**
 * Planner input schema - all data needed for plan generation
 */
export const PlannerInputSchema = z.object({
  weakAreas: z.array(WeakAreaInputSchema).max(10, "Maximum 10 weak areas"),
  lastWeekCompletion: z.number().min(0).max(100),
  recentMCQAccuracy: z.number().min(0).max(100),
  latestMood: z.string().nullable(),
  latestBlockers: z.string().nullable(),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Date must be in YYYY-MM-DD format"),
});

// Type exports for TypeScript
export type AIDayPlanItem = z.infer<typeof AIDayPlanItemSchema>;
export type AIDayPlan = z.infer<typeof AIDayPlanSchema>;
export type AIWeekSummary = z.infer<typeof AIWeekSummarySchema>;
export type WeakAreaInput = z.infer<typeof WeakAreaInputSchema>;
export type PlannerInput = z.infer<typeof PlannerInputSchema>;